config/routes.rb
Help::Application.routes.draw do
  resources :acceptors

  resources :users
  resources :home
  resources :people
  resources :ngos do 
    collection do
      get :states
    end
  end

  resources :educations do
     collection do
      post 'search'
    end
  end

 root :to => "home#index"

end

app/models/acceptor.rb
class Acceptor < ActiveRecord::Base
end

app/controllers/acceptors_controller.rb
class AcceptorsController < ApplicationController
  # GET /acceptors
  # GET /acceptors.json
  def index
    @acceptors = Acceptor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @acceptors }
    end
  end

  # GET /acceptors/1
  # GET /acceptors/1.json
  def show
    @acceptor = Acceptor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @acceptor }
    end
  end

  # GET /acceptors/new
  # GET /acceptors/new.json
  def new
    @acceptor = Acceptor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @acceptor }
    end
  end

  # GET /acceptors/1/edit
  def edit
    @acceptor = Acceptor.find(params[:id])
  end

  # POST /acceptors
  # POST /acceptors.json
  def create
    @acceptor = Acceptor.new(params[:acceptor])

    respond_to do |format|
      if @acceptor.save
        format.html { redirect_to @acceptor, notice: 'Acceptor was successfully created.' }
        format.json { render json: @acceptor, status: :created, location: @acceptor }
      else
        format.html { render action: "new" }
        format.json { render json: @acceptor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /acceptors/1
  # PUT /acceptors/1.json
  def update
    @acceptor = Acceptor.find(params[:id])

    respond_to do |format|
      if @acceptor.update_attributes(params[:acceptor])
        format.html { redirect_to @acceptor, notice: 'Acceptor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @acceptor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acceptors/1
  # DELETE /acceptors/1.json
  def destroy
    @acceptor = Acceptor.find(params[:id])
    @acceptor.destroy

    respond_to do |format|
      format.html { redirect_to acceptors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/acceptors_helper.rb
module AcceptorsHelper
end

app/views/acceptors/_form.html.erb
<%= form_for @acceptor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :address, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zipcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :zipcode, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :state_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :region, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :region, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :category_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                acceptors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/acceptors/edit.html.erb
<%- model_class = @acceptor.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/acceptors/index.html.erb
<%- model_class = Acceptor.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:state_id) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @acceptors.each do |acceptor| %>
      <tr>
        <td><%= link_to acceptor.id, acceptor_path(acceptor) %></td>
        <td><%= acceptor.first_name %></td>
        <td><%= acceptor.last_name %></td>
        <td><%= acceptor.address %></td>
        <td><%= acceptor.zipcode %></td>
        <td><%= acceptor.state_id %></td>
        <td><%= acceptor.region %></td>
        <td><%= acceptor.category_id %></td>
        <td><%=l acceptor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_acceptor_path(acceptor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      acceptor_path(acceptor),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_acceptor_path,
            :class => 'btn btn-primary' %>

app/views/acceptors/new.html.erb
<%- model_class = @acceptor.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/acceptors/show.html.erb
<%- model_class = @acceptor.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:first_name) %>:</strong><br>
  <%= @acceptor.first_name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:last_name) %>:</strong><br>
  <%= @acceptor.last_name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:address) %>:</strong><br>
  <%= @acceptor.address %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:zipcode) %>:</strong><br>
  <%= @acceptor.zipcode %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:state_id) %>:</strong><br>
  <%= @acceptor.state_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:region) %>:</strong><br>
  <%= @acceptor.region %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:category_id) %>:</strong><br>
  <%= @acceptor.category_id %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              acceptors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_acceptor_path(@acceptor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              acceptor_path(@acceptor),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>