config/routes.rb
Help::Application.routes.draw do
  resources :acceptors

  resources :users
  resources :home
  resources :people
  resources :ngos do 
    collection do
      get :states
    end
  end

  resources :educations do
     collection do
      post 'search'
    end
  end

 root :to => "home#index"

end

app/views/layouts/_choose_option.haml
/%h1 Choose Option
/= link_to image_tag('volunteer.png'), :action => :index
/= link_to image_tag('sponsor.png'), :action => :index

app/views/layouts/_people_photo_slider.html.haml
= javascript_include_tag 'jquery.1.6.4.min', 'jquery.slideviewer.1.2', 'jquery.easing.1.3.js'
#mygallary.svw
  %ul
    - people.each do |person|
      %li{:id => person.id}
        = image_tag person.photo.url
                 
              
:javascript
  displayOnMouseover()
  $(window).bind("load", function() {
  $("#mygallary").slideView({
  easeFunc: "easeInOutSine",
  easeTime: 500,
  uiBefore: true, //you can optionally draw the ui before the slider's images
  ttOpacity: 0.5,
  toolTip: true
  })
  })
  

app/views/layouts/application.html.haml
%head
  %title Help
  = stylesheet_link_tag "application"
  = javascript_include_tag "application"
  = csrf_meta_tag
%body
  #main
    #topBanner
      %center= image_tag "top_banner.gif"
    #tabs
      %center
        %ul
          %div{:style => "position:relative; display:inline;margin-left:-80px;"}
            %li= link_to 'Education', educations_path
          %div{:style => "position:relative; display:inline;margin-left:15px;"}
            %li= link_to 'Old-age Home',people_path
          %div{:style => "position:relative; display:inline;margin-left:15px;"}
            %li= link_to 'Orphanages',root_path
          %div{:style => "position:relative; display:inline;margin-left:15px;"}
            %li= link_to 'Medical Facilities',root_path
          %div{:style => "position:relative;display:inline;margin-left:15px;"}
            %li= link_to 'Provide Employment',root_path
          %div{:style => "position:relative; display:inline;margin-left:15px;"}
            %li= link_to '  Support ',root_path
    %center= yield
    %center= yield :scripts
    
    